addSbtPlugin("org.typelevel" % "sbt-tpolecat" % "0.5.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-github-actions" % "0.7.7")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.18.2")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.4")
